### ISSUE TITLE
How to disable a default mapping?

### ISSUE THREAD

**Issue by BSDxxxx** [dkarter/bullets.vim#57] opened 2020-03-14 04:12 UTC
Sorry, I'm new to vim, and there is no example in the help file.

How disable ```<space>x```? 
and
How to map it to another key?

**Comment by Melkster** [comment] 2020-04-08 21:59
Why did this issue get closed? I'm wondering the same thing. Is there a way to disable only `<leader>x` and keep all other default mappings?

**Comment by BSDxxxx** [comment] 2020-04-09 03:21
@Melkster Kind of solved this problem myself, I asked this question cause even I have remapped `<leader>x` like:
```
autocmd filetype vimwiki.markdown.pandoc nnoremap <buffer> <silent> <LEADER>x :VimwikiToggleListItem<CR>
```
It didn't work before. But somehow It works for now, not sure why.

I do not see how to disable `<LEADER>x` in help file. One solution for that is using `myafter.vim`:
create a file `~/.vim/after/plugin/after.vim`, and insert:
```
"this script will be executed after plugins have been loaded, but make sure it's in your vim run time path
unmap <Leader>x
```

**Comment by Melkster** [comment] 2020-04-09 09:23
@BSDxxxx What I'm looking to do is to remap the functionality of `<leader>x` to `<leader>X` because it conflicts with the [ConflictMotions](https://github.com/vim-scripts/ConflictMotions) plugin's mappings, which I would like to keep as they are. Your solution feels kind of messy and I think it would be nice if bullets.vim had something built in for purpose.

**Comment by BSDxxxx** [comment] 2020-04-09 09:52
@Melkster 
I'll reopen this issue for you.  
BTW, switch the position of bullets.vim and ComflictMotions in your vimrc may do the trick.

**Comment by Melkster** [comment] 2020-04-09 10:26
@BSDxxxx Thanks!

> BTW, switch the position of bullets.vim and ComflictMotions in your vimrc may do the trick.

The problem is that ConflictMotions has only mappings with one more characters after `x`, like `<leader>x>` etc. so it's not a direct map conflict, but I'm annoyed by the delay after checking a box using `<leader>x` since Vim is waiting for more potential characters for ConflictMotions and that's why I want to remap bullets.vim's `:ToggleCheckbox` to `<leader>X`.

**Comment by dkarter** [comment] 2020-05-05 17:02
@Melkster @BSDxxxx I agree that we should have more granularity in mapping configuration. I'll take a PR for that, otherwise it may be a little bit before I have time to do it myself.

**Comment by c02y** [comment] 2021-04-22 02:08
Hello, how can I disable `<ledaer>x`? Since I got several other keybindings like `<leader>xa` and `<leader>xd`, `<leader>x` is just a prefix, `<leader>x` in bullets.vim make them unaccessible, I would like to rebind `:ToggleCheckbox` to another mapping like `<leader>xx`.

**Comment by Melkster** [comment] 2021-04-22 09:27
@c02y I don't know how to disable `<leader>x`, but if you just add `nnoremap <leader>xx :ToggleCheckbox<CR>` it should not conflict with your other bindings.

**Comment by c02y** [comment] 2021-04-22 10:15
Yeah, sorry about that, since the binding of `<leader>x` is still listed in my `which-key` and it is still working, I thought the sub-keybindings under `<leader>x` are not working anymore, actually they are all working.

**Comment by wenzel-hoffman** [comment] 2022-09-12 20:21
@BSDxxxx I guess new change for making custom mappings would cover your needs. Look for `g:bullets_custom_mappings` in the README.

**Comment by dkarter** [comment] 2022-09-14 22:49
Thanks @wenzel-hoffman ! Closing this for now since the addition of `g:bullets_custom_mappings` along with `let g:bullets_set_mappings = 0` should provide an adequate solution.

**Closed by dkarter** 2022-09-14 22:49 UTC
Labels: question
